sudo: false
language: node_js
# NodeJS version
node_js:
  - 12
# Travis-CI Caching
cache: npm
# build `main` branch only
branches:
  only:
    - main
install:
  - npm install
script:
  - npm run build:umd
  - npm run build:esm
  - npm run build:cjs
  - npm run build:types
deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_API_TOKEN"
  skip_cleanup: true
  on:
    branch: main

